# Generated by Django 3.2.6 on 2021-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.CharField(choices=[('Gandaki', 'Gandaki'), ('Province No. 1', 'Province No. 1'), ('Province No. 2', 'Province No. 2'), ('Province No. 3', 'Province No. 3'), ('Sudurpashchim', 'Sudurpashchim'), ('Province No. 5', 'Province No. 5'), ('Karnali', 'Karnali')], max_length=50, null=True),
        ),
    ]
